config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :sessions => 'users/sessions',
  :registrations => 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root "events#index"
  resources :events do
    member do
      get :join
      delete :remove
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :participants, through: :events_participants_relationships, source: :user
  has_many :events_participants_relationships, dependent: :destroy
  has_many :organizers, through: :events_organizer_relationships, source: :user
  has_many :events_organizer_relationships, dependent: :destroy
  belongs_to :genre

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :schedule, presence: true
  validates :recruitment_numbers, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :participant_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def people_counter(ud)
    case ud
    when "up"
      update(recruitment_numbers: recruitment_numbers - 1, participant_count: participant_count + 1)
    when "down"
      update(recruitment_numbers: recruitment_numbers + 1, participant_count: participant_count - 1)
    end
    if participant_count == 0
      update(result: 1)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :show, :update, :join, :destroy, :remove]
  before_action :authenticate

  def index
    @search = Event.search(params[:q])
    if params[:q].present?
      @genre = params[:q][:genre_id_eq]
      @title = params[:q][:title_cont]
    end
    @events = @search.result.reorder("created_at DESC").page(params[:page]).per(20)
  end

  def new
    @event = Event.new
    @genre = Genre.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      current_user.holding_events << @event
      redirect_to events_path
    else
      render :new
    end
  end

  def update
    binding.pry
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def join
    @event.participants << current_user
    @event.people_counter("up")
  end

  def destroy
    @event.destroy
    redirect_to user_path(current_user)
  end

  def remove
    EventsParticipantsRelationship.find_by(user_id: current_user.id, event_id: @event.id).destroy
    @event.people_counter("down")
    redirect_to user_path(current_user)
  end

  private

  def event_params
    if params[:event][:result] == "1"
      params[:event][:recruitment_numbers] = 0
    end
    params.require(:event).permit(:title, :url, :image, :description, :schedule, :recruitment_numbers, :participant_count, :genre_id, :result)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.slim
- events.each do |event|
  .event.col-md-3.panel.panel-default
    .panel-body
      = link_to event_path(event) do
        = image_tag event.image, size: "200x200"
      = link_to event_path(event) do
        p
          = event.title
      | 開催日
      = event.schedule
      .counter.row
        .recruitment_number.col-md-4
          | 募集人数
          br
          = "残り#{event.recruitment_numbers}人"
        .participants.col-md-6
          | 現在の参加人数
          br
          = "#{event.participant_count}人"

app/views/events/_form.html.slim
= simple_form_for @event do |f|
  = f.error_notification

  .form-inputs.col-md-6
    = f.input :title
    = f.input :description
    = f.input :url
    = f.input :schedule, as: :date, use_month_numbers: true
    = f.input :recruitment_numbers
    = f.input :participant_count
    = f.input :image
    = f.association :genre
    = f.input :result, label: "募集を停止にする"
    = f.button :submit

app/views/events/edit.html.slim
.row.container
  h1
    | Event編集
  == render "form"

app/views/events/index.html.slim
.row
  h1
    | Event一覧
  .search_form
    = search_form_for @search, builder: SimpleForm::FormBuilder  do |f|
      .form-inputs
        .row
          .col-sm-4
            = f.input :title_cont, placeholder: "タイトル検索", input_html: { value: @title }
          //.col-sm-4
            = f.input :schedule_eq, placeholder: "開催日を選択", input_html: { value: @title, class: "datetimepicker" }, as: :string, use_month_numbers: true
          .col-sm-4
            = f.input :genre_id_eq, collection: Genre.all, label_method: :name,  value_method: :id, input_html: { value: @genre || "" }
      .form-actions
        = f.button :submit, "検索"
  = paginate @events
  .contents.row
    - @events.each do |event|
      .event.col-md-3
        .image
          = link_to event_path(event) do
            = image_tag event.image, size: "200x200"
        .title
          = link_to event_path(event) do
            h4
              = event.title
        .schedule
          | 開催日  
          = event.schedule
        .genre
          | ジャンル  
          = event.genre.try(:name)
        .counter.row
          .recruitment_number.col-md-4
            | 募集人数
            br
            = "残り#{event.recruitment_numbers}人"
          .participants.col-md-6
            | 現在の参加人数
            br
            = "#{event.participant_count}人"
        .commit_button
          - unless event.organizers.include?(current_user)
            - if event.result?
              = link_to "募集終了", "",disabled: true, class: "btn btn-default"
            - elsif event.participants.include?(current_user)
              = link_to "参加登録中", "", disabled: true, class: "btn btn-default"
            - else
              = link_to "参加", join_event_path(event), class: "btn btn-default"
  = paginate @events

app/views/events/join.html.slim
h1
  | 参加が確定しました

app/views/events/new.html.slim
.row.container
  h1
    | Event作成
  == render "form"

app/views/events/show.html.slim
.event.row
  .image.col-md-6
    = image_tag @event.image, size: "400x400"
  .contents.col-md-6
    .title
      h3
        = @event.title
    .holding_user
      | 主催者
      br
      = @event.organizers.first.name
    .schedule
      | 開催日
      br
      = @event.schedule
    .description
      | 詳細
      br
      = simple_format(@event.description)
    .url
      | イベントURL
      br
      = link_to @event.url, "#{@event.url}", target: "_blank"
    .counter.row
      .recruitment.col-md-6
        | 募集人数
        br
        = "#{@event.recruitment_numbers}人"
      .participants.col-md-6
        | 現在の参加人数
        br
        = "#{@event.participant_count}人"
  - if @event.organizers.include?(current_user)
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_event_path(@event), :class => 'btn btn-default'
    '
    = link_to t('.destroy', :default => t("helpers.links.destroy")), event_path(@event), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '本当に削除しますか?')) }, :class => 'btn btn-danger'
  - elsif @event.participants.include?(current_user)
    = link_to "参加をキャンセルする", remove_event_path(@event), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '参加をキャンセルしますか?')) }, :class => 'btn btn-danger'
.joiner_index.row
  h2
    | 参加者一覧
  - @event.participants.each do |user|
    .user.col-md-2
      = image_tag user.icon, size: "100x100"
      br
      h3
        = user.name