config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :sessions => 'users/sessions',
  :registrations => 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root "events#index"
  resources :events do
    member do
      get :join
      delete :remove
    end
  end
end

app/views/layouts/_footer.html.slim
footer.container-fluid
  small
    a href="/"  Copyright (C) 2013-2014 9ineBB All Rights Reserved.

app/views/layouts/_navigator.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .navbar-header
    a.navbar-brand href="#"  LOGO
    button.navbar-toggle data-target="#nav-content" data-toggle="collapse" type="button"
      span.icon-bar
      span.icon-bar
      span.icon-bar
  #nav-content.collapse.navbar-collapse
    ul.nav.navbar-nav
      - if user_signed_in?
        li
          = link_to "プログラムを作成", new_event_path
        li
          = link_to "プログラムを探す", events_path
        li
          = link_to "マイページ", user_path(current_user)
        li
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        li
          = link_to "Log in", new_session_path(resource_name)
        li
          = link_to "Sign up", new_registration_path(resource_name)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ComeWith
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body[id="#{controller_name}_#{action_name}"]
    == render "layouts/navigator"
    .container#main_content
      = yield
    == render "layouts/footer"